// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTKk1c3kbmzzoBEUluMOarvFJEU6Ebixk',
    appId: '1:955186772809:web:623aded354546c3d23f898',
    messagingSenderId: '955186772809',
    projectId: 'fir-task-bcc09',
    authDomain: 'fir-task-bcc09.firebaseapp.com',
    storageBucket: 'fir-task-bcc09.appspot.com',
    measurementId: 'G-F1MNSNSN5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-npS5qyaksdpwzc6ddrFFT3VVvBBSYmI',
    appId: '1:955186772809:android:69e4ff157a03acda23f898',
    messagingSenderId: '955186772809',
    projectId: 'fir-task-bcc09',
    storageBucket: 'fir-task-bcc09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUteiClPgK529BsREhoIg8lz6jmICteHU',
    appId: '1:955186772809:ios:89aa7b32f99d742323f898',
    messagingSenderId: '955186772809',
    projectId: 'fir-task-bcc09',
    storageBucket: 'fir-task-bcc09.appspot.com',
    iosBundleId: 'com.example.firebasetask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUteiClPgK529BsREhoIg8lz6jmICteHU',
    appId: '1:955186772809:ios:f479f83eada31ce423f898',
    messagingSenderId: '955186772809',
    projectId: 'fir-task-bcc09',
    storageBucket: 'fir-task-bcc09.appspot.com',
    iosBundleId: 'com.example.firebasetask.RunnerTests',
  );
}
